<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_</name>
   <tag></tag>
   <elementGuidId>62520db9-91c4-4ca1-8955-3096969de894</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root-master']/div/div/div/div[2]/div/div[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>12be14c8-564a-412f-b652-c62a6e179481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>arim_text-overflow menuItem___nOQU8 highlight___UcipK</value>
      <webElementGuid>a932f8e3-3549-4aa6-9243-12c3d5d8c2eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>_nk</name>
      <type>Main</type>
      <value>iArWnTS12</value>
      <webElementGuid>e1481b53-5cab-4aa1-b1c3-e280e16e0cb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>系统管理</value>
      <webElementGuid>e4f396dd-b2e1-4a67-9f39-a2136191c650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root-master&quot;)/div[@class=&quot;navs___X754f&quot;]/div[@class=&quot;ant-app css-var-r0&quot;]/div[@class=&quot;navigationWrapper___te3Kc&quot;]/div[@class=&quot;middle___F8CK_&quot;]/div[@class=&quot;menuWrapper___xSApn&quot;]/div[@class=&quot;arim_text-overflow menuItem___nOQU8 highlight___UcipK&quot;]</value>
      <webElementGuid>d4c27dab-0ca4-492b-8afe-f3b780bd3355</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root-master']/div/div/div/div[2]/div/div[6]</value>
      <webElementGuid>24c44715-6737-4d13-bd14-ba5c8abd31c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='基础配置'])[1]/following::div[1]</value>
      <webElementGuid>6477bf6e-ec94-4cec-ae41-31525f055abd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='组炉组浇'])[1]/following::div[2]</value>
      <webElementGuid>028c06d7-7e5a-4f00-9b31-3c154ba0386a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='admin'])[1]/preceding::div[2]</value>
      <webElementGuid>7ae08570-212e-49b3-9ec1-dc7a5efb2d92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='生产订单'])[1]/preceding::div[5]</value>
      <webElementGuid>8140c908-72c4-40c7-831c-4a29dc4ae8c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='系统管理']/parent::*</value>
      <webElementGuid>7953aee8-0ed6-4fc9-a3ac-f2a7c81abb6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]</value>
      <webElementGuid>115ee327-1ec6-4180-ba60-220593d78368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '系统管理' or . = '系统管理')]</value>
      <webElementGuid>a4c622da-be18-426d-83ef-1e99458a50c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
